//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estacionamiento()
        {
            this.Reporte = new HashSet<Reporte>();
        }
    
        public int IdEstacionamiento { get; set; }
        public int LugarEstacionamiento { get; set; }
        public System.DateTime HoraEntrada { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public bool EstacionamientoOcupado { get; set; }
        public int idBicicleta { get; set; }
        public int idTrabajador { get; set; }
    
        public virtual Bicicleta Bicicleta { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reporte> Reporte { get; set; }
    }
}
